// Code generated by MockGen. DO NOT EDIT.
// Source: controller/pkg/remoteenforcer/internal/counterclient/interfaces.go

// Package mockcounterclient is a generated GoMock package.
package mockcounterclient

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCounterClient is a mock of CounterClient interface
// nolint
type MockCounterClient struct {
	ctrl     *gomock.Controller
	recorder *MockCounterClientMockRecorder
}

// MockCounterClientMockRecorder is the mock recorder for MockCounterClient
// nolint
type MockCounterClientMockRecorder struct {
	mock *MockCounterClient
}

// NewMockCounterClient creates a new mock instance
// nolint
func NewMockCounterClient(ctrl *gomock.Controller) *MockCounterClient {
	mock := &MockCounterClient{ctrl: ctrl}
	mock.recorder = &MockCounterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (m *MockCounterClient) EXPECT() *MockCounterClientMockRecorder {
	return m.recorder
}

// Run mocks base method
// nolint
func (m *MockCounterClient) Run(ctx context.Context) error {
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
// nolint
func (mr *MockCounterClientMockRecorder) Run(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCounterClient)(nil).Run), ctx)
}
