// Code generated by MockGen. DO NOT EDIT.
// Source: monitor/processor/interfaces.go

// Package mockprocessor is a generated GoMock package.
package mockprocessor

import (
	reflect "reflect"

	eventinfo "github.com/aporeto-inc/trireme-lib/monitor/eventinfo"
	gomock "github.com/golang/mock/gomock"
)

// MockEventProcessor is a mock of EventProcessor interface
// nolint
type MockEventProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockEventProcessorMockRecorder
}

// MockEventProcessorMockRecorder is the mock recorder for MockEventProcessor
// nolint
type MockEventProcessorMockRecorder struct {
	mock *MockEventProcessor
}

// NewMockEventProcessor creates a new mock instance
// nolint
func NewMockEventProcessor(ctrl *gomock.Controller) *MockEventProcessor {
	mock := &MockEventProcessor{ctrl: ctrl}
	mock.recorder = &MockEventProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (m *MockEventProcessor) EXPECT() *MockEventProcessorMockRecorder {
	return m.recorder
}

// Start mocks base method
// nolint
func (m *MockEventProcessor) Start(eventInfo *eventinfo.EventInfo) error {
	ret := m.ctrl.Call(m, "Start", eventInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
// nolint
func (mr *MockEventProcessorMockRecorder) Start(eventInfo interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEventProcessor)(nil).Start), eventInfo)
}

// Stop mocks base method
// nolint
func (m *MockEventProcessor) Stop(eventInfo *eventinfo.EventInfo) error {
	ret := m.ctrl.Call(m, "Stop", eventInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop
// nolint
func (mr *MockEventProcessorMockRecorder) Stop(eventInfo interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEventProcessor)(nil).Stop), eventInfo)
}

// Create mocks base method
// nolint
func (m *MockEventProcessor) Create(eventInfo *eventinfo.EventInfo) error {
	ret := m.ctrl.Call(m, "Create", eventInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
// nolint
func (mr *MockEventProcessorMockRecorder) Create(eventInfo interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventProcessor)(nil).Create), eventInfo)
}

// Destroy mocks base method
// nolint
func (m *MockEventProcessor) Destroy(eventInfo *eventinfo.EventInfo) error {
	ret := m.ctrl.Call(m, "Destroy", eventInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy
// nolint
func (mr *MockEventProcessorMockRecorder) Destroy(eventInfo interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockEventProcessor)(nil).Destroy), eventInfo)
}

// Pause mocks base method
// nolint
func (m *MockEventProcessor) Pause(eventInfo *eventinfo.EventInfo) error {
	ret := m.ctrl.Call(m, "Pause", eventInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause
// nolint
func (mr *MockEventProcessorMockRecorder) Pause(eventInfo interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockEventProcessor)(nil).Pause), eventInfo)
}

// ReSync mocks base method
// nolint
func (m *MockEventProcessor) ReSync(EventInfo *eventinfo.EventInfo) error {
	ret := m.ctrl.Call(m, "ReSync", EventInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReSync indicates an expected call of ReSync
// nolint
func (mr *MockEventProcessorMockRecorder) ReSync(EventInfo interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReSync", reflect.TypeOf((*MockEventProcessor)(nil).ReSync), EventInfo)
}
