// Code generated by MockGen. DO NOT EDIT.
// Source: controller/interfaces.go

package mockcontroller

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	packettracing "go.aporeto.io/trireme-lib/v11/controller/pkg/packettracing"
	secrets "go.aporeto.io/trireme-lib/v11/controller/pkg/secrets"
	runtime "go.aporeto.io/trireme-lib/v11/controller/runtime"
	policy "go.aporeto.io/trireme-lib/v11/policy"
)

// MockTriremeController is a mock of TriremeController interface
// nolint
type MockTriremeController struct {
	ctrl     *gomock.Controller
	recorder *MockTriremeControllerMockRecorder
}

// MockTriremeControllerMockRecorder is the mock recorder for MockTriremeController
// nolint
type MockTriremeControllerMockRecorder struct {
	mock *MockTriremeController
}

// NewMockTriremeController creates a new mock instance
// nolint
func NewMockTriremeController(ctrl *gomock.Controller) *MockTriremeController {
	mock := &MockTriremeController{ctrl: ctrl}
	mock.recorder = &MockTriremeControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (_m *MockTriremeController) EXPECT() *MockTriremeControllerMockRecorder {
	return _m.recorder
}

// Run mocks base method
// nolint
func (_m *MockTriremeController) Run(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
// nolint
func (_mr *MockTriremeControllerMockRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Run", reflect.TypeOf((*MockTriremeController)(nil).Run), arg0)
}

// CleanUp mocks base method
// nolint
func (_m *MockTriremeController) CleanUp() error {
	ret := _m.ctrl.Call(_m, "CleanUp")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanUp indicates an expected call of CleanUp
// nolint
func (_mr *MockTriremeControllerMockRecorder) CleanUp() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CleanUp", reflect.TypeOf((*MockTriremeController)(nil).CleanUp))
}

// Enforce mocks base method
// nolint
func (_m *MockTriremeController) Enforce(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime) error {
	ret := _m.ctrl.Call(_m, "Enforce", ctx, puID, policy, runtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enforce indicates an expected call of Enforce
// nolint
func (_mr *MockTriremeControllerMockRecorder) Enforce(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Enforce", reflect.TypeOf((*MockTriremeController)(nil).Enforce), arg0, arg1, arg2, arg3)
}

// UnEnforce mocks base method
// nolint
func (_m *MockTriremeController) UnEnforce(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime) error {
	ret := _m.ctrl.Call(_m, "UnEnforce", ctx, puID, policy, runtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnEnforce indicates an expected call of UnEnforce
// nolint
func (_mr *MockTriremeControllerMockRecorder) UnEnforce(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UnEnforce", reflect.TypeOf((*MockTriremeController)(nil).UnEnforce), arg0, arg1, arg2, arg3)
}

// UpdatePolicy mocks base method
// nolint
func (_m *MockTriremeController) UpdatePolicy(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime) error {
	ret := _m.ctrl.Call(_m, "UpdatePolicy", ctx, puID, policy, runtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePolicy indicates an expected call of UpdatePolicy
// nolint
func (_mr *MockTriremeControllerMockRecorder) UpdatePolicy(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdatePolicy", reflect.TypeOf((*MockTriremeController)(nil).UpdatePolicy), arg0, arg1, arg2, arg3)
}

// UpdateSecrets mocks base method
// nolint
func (_m *MockTriremeController) UpdateSecrets(secrets secrets.Secrets) error {
	ret := _m.ctrl.Call(_m, "UpdateSecrets", secrets)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecrets indicates an expected call of UpdateSecrets
// nolint
func (_mr *MockTriremeControllerMockRecorder) UpdateSecrets(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdateSecrets", reflect.TypeOf((*MockTriremeController)(nil).UpdateSecrets), arg0)
}

// UpdateConfiguration mocks base method
// nolint
func (_m *MockTriremeController) UpdateConfiguration(cfg *runtime.Configuration) error {
	ret := _m.ctrl.Call(_m, "UpdateConfiguration", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfiguration indicates an expected call of UpdateConfiguration
// nolint
func (_mr *MockTriremeControllerMockRecorder) UpdateConfiguration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdateConfiguration", reflect.TypeOf((*MockTriremeController)(nil).UpdateConfiguration), arg0)
}

// EnableDatapathPacketTracing mocks base method
// nolint
func (_m *MockTriremeController) EnableDatapathPacketTracing(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime, direction packettracing.TracingDirection, interval time.Duration) error {
	ret := _m.ctrl.Call(_m, "EnableDatapathPacketTracing", ctx, puID, policy, runtime, direction, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableDatapathPacketTracing indicates an expected call of EnableDatapathPacketTracing
// nolint
func (_mr *MockTriremeControllerMockRecorder) EnableDatapathPacketTracing(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EnableDatapathPacketTracing", reflect.TypeOf((*MockTriremeController)(nil).EnableDatapathPacketTracing), arg0, arg1, arg2, arg3, arg4, arg5)
}

// EnableIPTablesPacketTracing mocks base method
// nolint
func (_m *MockTriremeController) EnableIPTablesPacketTracing(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime, interval time.Duration) error {
	ret := _m.ctrl.Call(_m, "EnableIPTablesPacketTracing", ctx, puID, policy, runtime, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableIPTablesPacketTracing indicates an expected call of EnableIPTablesPacketTracing
// nolint
func (_mr *MockTriremeControllerMockRecorder) EnableIPTablesPacketTracing(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EnableIPTablesPacketTracing", reflect.TypeOf((*MockTriremeController)(nil).EnableIPTablesPacketTracing), arg0, arg1, arg2, arg3, arg4)
}

// Ping mocks base method
// nolint
func (_m *MockTriremeController) Ping(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime, pingConfig *policy.PingConfig) error {
	ret := _m.ctrl.Call(_m, "Ping", ctx, puID, policy, runtime, pingConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping
// nolint
func (_mr *MockTriremeControllerMockRecorder) Ping(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Ping", reflect.TypeOf((*MockTriremeController)(nil).Ping), arg0, arg1, arg2, arg3, arg4)
}

// MockDebugInfo is a mock of DebugInfo interface
// nolint
type MockDebugInfo struct {
	ctrl     *gomock.Controller
	recorder *MockDebugInfoMockRecorder
}

// MockDebugInfoMockRecorder is the mock recorder for MockDebugInfo
// nolint
type MockDebugInfoMockRecorder struct {
	mock *MockDebugInfo
}

// NewMockDebugInfo creates a new mock instance
// nolint
func NewMockDebugInfo(ctrl *gomock.Controller) *MockDebugInfo {
	mock := &MockDebugInfo{ctrl: ctrl}
	mock.recorder = &MockDebugInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (_m *MockDebugInfo) EXPECT() *MockDebugInfoMockRecorder {
	return _m.recorder
}

// EnableDatapathPacketTracing mocks base method
// nolint
func (_m *MockDebugInfo) EnableDatapathPacketTracing(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime, direction packettracing.TracingDirection, interval time.Duration) error {
	ret := _m.ctrl.Call(_m, "EnableDatapathPacketTracing", ctx, puID, policy, runtime, direction, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableDatapathPacketTracing indicates an expected call of EnableDatapathPacketTracing
// nolint
func (_mr *MockDebugInfoMockRecorder) EnableDatapathPacketTracing(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EnableDatapathPacketTracing", reflect.TypeOf((*MockDebugInfo)(nil).EnableDatapathPacketTracing), arg0, arg1, arg2, arg3, arg4, arg5)
}

// EnableIPTablesPacketTracing mocks base method
// nolint
func (_m *MockDebugInfo) EnableIPTablesPacketTracing(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime, interval time.Duration) error {
	ret := _m.ctrl.Call(_m, "EnableIPTablesPacketTracing", ctx, puID, policy, runtime, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableIPTablesPacketTracing indicates an expected call of EnableIPTablesPacketTracing
// nolint
func (_mr *MockDebugInfoMockRecorder) EnableIPTablesPacketTracing(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EnableIPTablesPacketTracing", reflect.TypeOf((*MockDebugInfo)(nil).EnableIPTablesPacketTracing), arg0, arg1, arg2, arg3, arg4)
}

// Ping mocks base method
// nolint
func (_m *MockDebugInfo) Ping(ctx context.Context, puID string, policy *policy.PUPolicy, runtime *policy.PURuntime, pingConfig *policy.PingConfig) error {
	ret := _m.ctrl.Call(_m, "Ping", ctx, puID, policy, runtime, pingConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping
// nolint
func (_mr *MockDebugInfoMockRecorder) Ping(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Ping", reflect.TypeOf((*MockDebugInfo)(nil).Ping), arg0, arg1, arg2, arg3, arg4)
}
