// Code generated by MockGen. DO NOT EDIT.
// Source: controller/pkg/remoteenforcer/interfaces.go

package mockremoteenforcer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	rpcwrapper "go.aporeto.io/trireme-lib/v11/controller/internal/enforcer/utils/rpcwrapper"
)

// MockRemoteIntf is a mock of RemoteIntf interface
// nolint
type MockRemoteIntf struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteIntfMockRecorder
}

// MockRemoteIntfMockRecorder is the mock recorder for MockRemoteIntf
// nolint
type MockRemoteIntfMockRecorder struct {
	mock *MockRemoteIntf
}

// NewMockRemoteIntf creates a new mock instance
// nolint
func NewMockRemoteIntf(ctrl *gomock.Controller) *MockRemoteIntf {
	mock := &MockRemoteIntf{ctrl: ctrl}
	mock.recorder = &MockRemoteIntfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (_m *MockRemoteIntf) EXPECT() *MockRemoteIntfMockRecorder {
	return _m.recorder
}

// InitEnforcer mocks base method
// nolint
func (_m *MockRemoteIntf) InitEnforcer(req rpcwrapper.Request, resp *rpcwrapper.Response) error {
	ret := _m.ctrl.Call(_m, "InitEnforcer", req, resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitEnforcer indicates an expected call of InitEnforcer
// nolint
func (_mr *MockRemoteIntfMockRecorder) InitEnforcer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InitEnforcer", reflect.TypeOf((*MockRemoteIntf)(nil).InitEnforcer), arg0, arg1)
}

// Unenforce mocks base method
// nolint
func (_m *MockRemoteIntf) Unenforce(req rpcwrapper.Request, resp *rpcwrapper.Response) error {
	ret := _m.ctrl.Call(_m, "Unenforce", req, resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unenforce indicates an expected call of Unenforce
// nolint
func (_mr *MockRemoteIntfMockRecorder) Unenforce(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Unenforce", reflect.TypeOf((*MockRemoteIntf)(nil).Unenforce), arg0, arg1)
}

// Enforce mocks base method
// nolint
func (_m *MockRemoteIntf) Enforce(req rpcwrapper.Request, resp *rpcwrapper.Response) error {
	ret := _m.ctrl.Call(_m, "Enforce", req, resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enforce indicates an expected call of Enforce
// nolint
func (_mr *MockRemoteIntfMockRecorder) Enforce(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Enforce", reflect.TypeOf((*MockRemoteIntf)(nil).Enforce), arg0, arg1)
}

// EnforcerExit mocks base method
// nolint
func (_m *MockRemoteIntf) EnforcerExit(req rpcwrapper.Request, resp *rpcwrapper.Response) error {
	ret := _m.ctrl.Call(_m, "EnforcerExit", req, resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnforcerExit indicates an expected call of EnforcerExit
// nolint
func (_mr *MockRemoteIntfMockRecorder) EnforcerExit(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "EnforcerExit", reflect.TypeOf((*MockRemoteIntf)(nil).EnforcerExit), arg0, arg1)
}
