// Code generated by MockGen. DO NOT EDIT.
// Source: monitor/interfaces.go

package mockmonitor

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "go.aporeto.io/trireme-lib/v11/monitor/config"
	registerer "go.aporeto.io/trireme-lib/v11/monitor/registerer"
)

// MockMonitor is a mock of Monitor interface
// nolint
type MockMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorMockRecorder
}

// MockMonitorMockRecorder is the mock recorder for MockMonitor
// nolint
type MockMonitorMockRecorder struct {
	mock *MockMonitor
}

// NewMockMonitor creates a new mock instance
// nolint
func NewMockMonitor(ctrl *gomock.Controller) *MockMonitor {
	mock := &MockMonitor{ctrl: ctrl}
	mock.recorder = &MockMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (_m *MockMonitor) EXPECT() *MockMonitorMockRecorder {
	return _m.recorder
}

// Run mocks base method
// nolint
func (_m *MockMonitor) Run(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
// nolint
func (_mr *MockMonitorMockRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Run", reflect.TypeOf((*MockMonitor)(nil).Run), arg0)
}

// UpdateConfiguration mocks base method
// nolint
func (_m *MockMonitor) UpdateConfiguration(ctx context.Context, config *config.MonitorConfig) error {
	ret := _m.ctrl.Call(_m, "UpdateConfiguration", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfiguration indicates an expected call of UpdateConfiguration
// nolint
func (_mr *MockMonitorMockRecorder) UpdateConfiguration(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdateConfiguration", reflect.TypeOf((*MockMonitor)(nil).UpdateConfiguration), arg0, arg1)
}

// Resync mocks base method
// nolint
func (_m *MockMonitor) Resync(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "Resync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resync indicates an expected call of Resync
// nolint
func (_mr *MockMonitorMockRecorder) Resync(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Resync", reflect.TypeOf((*MockMonitor)(nil).Resync), arg0)
}

// MockImplementation is a mock of Implementation interface
// nolint
type MockImplementation struct {
	ctrl     *gomock.Controller
	recorder *MockImplementationMockRecorder
}

// MockImplementationMockRecorder is the mock recorder for MockImplementation
// nolint
type MockImplementationMockRecorder struct {
	mock *MockImplementation
}

// NewMockImplementation creates a new mock instance
// nolint
func NewMockImplementation(ctrl *gomock.Controller) *MockImplementation {
	mock := &MockImplementation{ctrl: ctrl}
	mock.recorder = &MockImplementationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
// nolint
func (_m *MockImplementation) EXPECT() *MockImplementationMockRecorder {
	return _m.recorder
}

// Run mocks base method
// nolint
func (_m *MockImplementation) Run(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
// nolint
func (_mr *MockImplementationMockRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Run", reflect.TypeOf((*MockImplementation)(nil).Run), arg0)
}

// SetupConfig mocks base method
// nolint
func (_m *MockImplementation) SetupConfig(registerer registerer.Registerer, cfg interface{}) error {
	ret := _m.ctrl.Call(_m, "SetupConfig", registerer, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupConfig indicates an expected call of SetupConfig
// nolint
func (_mr *MockImplementationMockRecorder) SetupConfig(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetupConfig", reflect.TypeOf((*MockImplementation)(nil).SetupConfig), arg0, arg1)
}

// SetupHandlers mocks base method
// nolint
func (_m *MockImplementation) SetupHandlers(c *config.ProcessorConfig) {
	_m.ctrl.Call(_m, "SetupHandlers", c)
}

// SetupHandlers indicates an expected call of SetupHandlers
// nolint
func (_mr *MockImplementationMockRecorder) SetupHandlers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SetupHandlers", reflect.TypeOf((*MockImplementation)(nil).SetupHandlers), arg0)
}

// Resync mocks base method
// nolint
func (_m *MockImplementation) Resync(ctx context.Context) error {
	ret := _m.ctrl.Call(_m, "Resync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resync indicates an expected call of Resync
// nolint
func (_mr *MockImplementationMockRecorder) Resync(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Resync", reflect.TypeOf((*MockImplementation)(nil).Resync), arg0)
}
